### ISSUE TITLE
Redirects to /login instead of /hub/login when navigating to a /hub page

### ISSUE THREAD

**Issue by RamiMustaklem** [getcandy/candy-store#5]
When the session has expired while navigating to a /hub page the application redirects to the default /login page.

Resulting in an error:
`ErrorException (E_ERROR)
Server error: `POST http://local.getcandy.com/api/oauth/token` resulted in a `500 Internal Server Error` response: <!DOCTYPE html><!-- ErrorException: Undefined variable: language (View: /resources/ (truncated...) (View: /resources/views/_layouts/base.blade.php) (View: /resources/views/_layouts/base.blade.php)`

**Comment by alecritson** [comment]
This will be fixed in the next release
